### ISSUE TITLE
"I need more information" on pages of some tools are not aligned correctly

### ISSUE THREAD

**Issue by msrubar** [OpenSCAP/website#100]
At these pages:

1. https://www-rhopenscap.rhcloud.com/tools/openscap-daemon/
2. https://www-rhopenscap.rhcloud.com/tools/scap-workbench/
3. https://www-rhopenscap.rhcloud.com/tools/openscap-base/

in the support sections the "I need more information" is not aligned correctly.

**Comment by lhorakov** [comment]
Think it's solved, please check it out.

**Comment by msrubar** [comment]
I can still see the issue on the daemon page
https://www-rhopenscap.rhcloud.com/tools/openscap-daemon/
