### ISSUE TITLE
Getting started wireframe

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#104]
https://www-rhopenscap.rhcloud.com/resources/getting-started/ needs a wireframe and nice design. It's a highly discoverable page from the homepage so I'd say this is a release blocker.

**Comment by lhorakov** [comment]
Almost done - almooost.

**Comment by mpreisler** [comment]
I would like to voice my concern with the direction of the page. Yes, it's getting flashy and modern but at the same time it's getting frustrating. While I am reading the text in the complex passages the carousel moves forward. IMO we should just dress it up but keep it in an article form.

**Comment by msrubar** [comment]
I also noticed this on the [SCE page](https://www-rhopenscap.rhcloud.com/features/other-standards/sce/). The wireframe of the page looks pretty nice and I wouldn't be able to design it better but IMHO I think it's too much for a technical article.

**Comment by jan-cerny** [comment]
@mpreisler +1
I suggest something like this page: https://pages.github.com/ 
Author of the text, @ybznek, had also some ideas.

**Comment by mpreisler** [comment]
@jan-cerny +1 that's a nice modern page that is also usable from a UX standpoint.

**Comment by lhorakov** [comment]
I'm pleased to announce you that I consider it done. Please check it out: 
http://www-rhopenscap.rhcloud.com/getting-started/

**Comment by mpreisler** [comment]
Nice! This is a big improvement, thanks!
