### ISSUE TITLE
Set up google analytics and google webmaster tools

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#106]
Not a critical issue but a low hanging fruit that would help us figure out what parts of the site are the most popular.

I believe @pvrabec has an account so ideally the services will be tied to that.

**Comment by msrubar** [comment]
It would be great to have a list of most read tutorials which could be shown at the [getting started](https://www-rhopenscap.rhcloud.com/resources/getting-started/) page in the section **Where to go from here.**

**Comment by mpreisler** [comment]
Done. I have set up the site with the google analytics tracking ID. Once it goes live the tracking will work.
