### ISSUE TITLE
Involve the community in portal content review

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#107]
This is just an idea and not really an issue.

We are going *release candidate* next Thursday - 2015-10-22. It might be a good idea to send the URL to open-scap-list, scap-security-guide list and the OpenSCAP twitter. Anybody with a github account can open an issue here. Some of our community members are more experienced in talking about SCAP than we are, perhaps we will get some good constructive feedback.

What do you think? I volunteer to write the emails if we agree to do this.

**Comment by msrubar** [comment]
I think it's a great idea and a chance to get some feedback from people that have different point of view then us.

**Comment by iankko** [comment]
+1

**Comment by lhorakov** [comment]
But that way we will publish the portal and I thought that we could publish it the 3rd of November, on OpenSCAPs 7th birthday. :)
We could do these things that they and consider it as officially published. No?

**Comment by mpreisler** [comment]
We could. The downside to doing this is that the release will not be as special and surprising as if we release out of the blue :-)

**Comment by mpreisler** [comment]
Lets do this after GA.

**Comment by lhorakov** [comment]
Thing you've done it already, close? @mpreisler

**Comment by mpreisler** [comment]
Yes
