### ISSUE TITLE
Use lightbox for screenshots in tutorials

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#112]
Helps the UX, the user stays in the same position in the tutorial and can zoom in on a screenshot. After the screenshot is closed the user can resume reading.

I have no idea how hard this is to accomplish but I think it should be simple. If that's not the case please move it to 2.0.

**Comment by lhorakov** [comment]
Done. If there would be any other images outside the tutorials, please send me the link of subpage as I could implement it also there. Thx

**Comment by ybznek** [comment]
I am writing new tutorial right now, how can I add it?
