### ISSUE TITLE
Provide logo for puppet-openscap and ruby-openscap projects

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#114]
Based on the requirement I have updated the "Ruby" language section of the:
   ```Home > Resources > Contribute```

page to include also the [puppet-openscap](https://github.com/OpenSCAP/puppet-openscap) and [ruby-openscap](https://github.com/OpenSCAP/ruby-openscap) sub-projects / components.

The issue is these two sub-projects so far don't have a dedicated icons (AFAIK), so clicking the ```Ruby``` language right now produces the image like attached below.
![screenshot](https://cloud.githubusercontent.com/assets/8414918/10666874/83e10610-78d4-11e5-8ce0-62d08f974485.png)

Therefore please create the icons for:
* puppet-openscap, and
* ruby-openscap

sub-projects so we can follow the layout / scheme as for other projects in the ```Contribute``` page currently.

Thank you, Jan.

**Comment by isimluk** [comment]
There have been some lame by me for puppet-* and ruby-*. https://isimluk.fedorapeople.org/openscap/icons.tar.bz2 However, they are very lame.

**Comment by mpreisler** [comment]
IMO this is not even close to `release_blocker`, it is milestone 1.0 though.

**Comment by lhorakov** [comment]
Done. Please, check it out of those logos are appropriate. Maybe it will not be visible very good, because it's small, so here are the logos:

![ruby-openscap](https://cloud.githubusercontent.com/assets/13556662/10695723/8358caee-79a5-11e5-9a5c-e6e8073aba70.png)
![openscap-puppet](https://cloud.githubusercontent.com/assets/13556662/10695722/8356ad9a-79a5-11e5-9d0b-096b3f163d43.png)

**Comment by iankko** [comment]
@lhorakov 
> Done. Please, check it out of those logos are appropriate. Maybe it will not be visible very good, because it's small, so here are the logos:

Thank you for this effort, Lenka! They look great IMHO.

One small issue though. Having had visited current (as of 2015-10-26) version of
```Home > Resources > Contribute``` page and selecting ```Ruby``` as language of my choose,
IMHO the circle in puppet-openscap logo case is a bit bigger than for the remaining two logos (ruby-openscap && SCAPTimony) =>

Small request -- would it be possible the circles in all these three logos to have the very same size?
(so they look uniform)

Thank you in advance!, Jan.

**Comment by lhorakov** [comment]
Done :)
