### ISSUE TITLE
Fix acronym lightbox on Acronyms page

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/website#117]
http://www-rhopenscap.rhcloud.com/resources/acronyms/

There are links to XCCDF, OVAL, from "SDS", but noting happens when I click on them.

**Comment by jan-cerny** [comment]
I think we don't need acronym lightboxes on "Acronyms" page, because they're explained on same page. Users aren't so stupid. I suggest removing these links instead of fixing them.

**Comment by lhorakov** [comment]
It was a bug, It doesn't supposed to be there. Thx
