### ISSUE TITLE
Page Map

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#122]
Generate page map of OpenSCAP Portal for better orientation and SEO.

**Comment by lhorakov** [comment]
Postoponed cause future change of domain.

**Comment by mpreisler** [comment]
Which wordpress plugin do you plan to use?

**Comment by lhorakov** [comment]
I thought that this one could be good:
https://wordpress.org/plugins/google-sitemap-generator/

**Comment by mpreisler** [comment]
I have added /sitemap.xml to google webmaster tools.

Is there anything else we need to do in this ticket?

**Comment by lhorakov** [comment]
I'm thinking about creating this sitemap page for users. Like in footer there would be Site Map, so not only for Google.

**Comment by lhorakov** [comment]
Done. Find it if you can!
