### ISSUE TITLE
Move acronyms to the place they can be edited easily.

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#130]
The acronyms are currently defined in the javascript somewhere on the wp instance. I have couple of improvements, but no access rights, does it make sense to push the javascript to this git repo?

**Comment by lhorakov** [comment]
Pust it here and I will make the magic

**Comment by mpreisler** [comment]
It's fairly problematic to load javascript from github on the site. Doesn't it make more sense to give Simon access to the openshift instance? Can you tell me what's your openshift account name?

**Comment by lhorakov** [comment]
Simon's says: I am afraid I don't have any.

**Comment by isimluk** [comment]
Ok, based on the discussion with Martin, this does not make sense ATM.
