### ISSUE TITLE
Ask contributors

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#131]
http://www-rhopenscap.rhcloud.com/resources/about-team/
Click on Lenka Horáková.

You can see below two icons of Behance, Blog and Linkedin.
There are 5 icons, from which they can choose and so they can publish there:
behance, blog, linkedin, twitter and/or github.

The number of icons which they choose is up to them.

**Comment by isimluk** [comment]
Removing myself as a assignee, I don't expect to have time allocation for this. Anyone can take it.

**Comment by lhorakov** [comment]
As this is not so urgent and also we already have the most basic information about contributors, I'm removing this to milestone 2. Also an other possible solution is to let the people to know that they can ask for adding a few personal links into their profile box, but that it's not obligatory.

**Comment by yuumasato** [comment]
We already have basic information from contributors from github.
