### ISSUE TITLE
provide replacement for /page/Windows

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#132]
Apparently it was a popular page with 29 links leading to it and quite some traffic.

EDIT: Typo in the link count, oops!

**Comment by lhorakov** [comment]
Why? How? How? :D What?

**Comment by mpreisler** [comment]
It is one of the top 404 pages. Google webmaster tools says 29 links with these 5 top domains:

redhat.com
osdir.com
marc.info
fedorahosted.org
spiceworks.com

Previously the page explained how to build openscap for Windows. Now I think we should first say that we have some prebuilt stuff for Windows and perhaps the user wants that. If not we can explain how to build OpenSCAP on Windows. We already have some content, see http://martin.preisler.me/2015/02/openscap-and-scap-workbench-on-windows/

**Comment by iankko** [comment]
Assuming the reason behind attendance of this page being people searching how to use the tools from OpenSCAP ecosystem on Microsoft Windows OS. Though not available right now for all of the tools from the suite, we probably could mention the SCAP Workbench tools is available for MS Windows already etc.

**Comment by mpreisler** [comment]
I have fixed some heavily linked pages:
/page/Special:Specialpages	7,870	redirected to /
/page/Maillist	7,771	redirected this to /resources/support/
/page/Links	6,796	redirected this to /resources/documentation/

We have no replacement for:
/page/Debug	93

**Comment by lhorakov** [comment]
Ahh, I get it know. Those are like old links, and now everyone has it saved in their cookiebrowsie and they are 404fulling our page... aaa-haa!

I would send every page for which we do not have replacement to /

**Comment by lhorakov** [comment]
Sending to 404: Page not found. Done

**Comment by mpreisler** [comment]
Wtf, 404 doesn't fix this issue. Keep it open, I will write the content.

**Comment by isimluk** [comment]
We can have temporarily redirects like:

open-scap.org/page/Windows --> https://github.com/OpenSCAP/openscap/blob/maint-1.2/docs/manual/manual.adoc#building-openscap-on-windows
http://www.open-scap.org/page/Debug --> https://github.com/OpenSCAP/openscap/blob/maint-1.2/docs/manual/manual.adoc#debugging

Not ideal, but good interim solution.

**Comment by mpreisler** [comment]
Thanks for the links, Simon! I have added the redirects. I will keep this open to track creation of a proper page.

**Comment by mpreisler** [comment]
Let's keep just the redirects, I thought about this and I believe this information should be in the git repository, not on the website.
