### ISSUE TITLE
[RFE] Start using the new lightbox approach for images in tutorials in general

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#134]
The recent version (as of 2015-11-02) of OpenSCAP portal started using the lightbox mechanism for images provided within tutorials section (see example below as currently present under
```
Home > Tools > OSCAP Anaconda Addon > Documentation > Install PCI-DSS compliant RHEL-7.2 
```
location:

![screenshot](https://cloud.githubusercontent.com/assets/8414918/10886811/29fe41e0-8184-11e5-99bb-316c1d6c987a.png)

RFE -- It would be nice if the portal pages would be consistent and every image provided within the content (not just in tutorials, but also in standalone pages would display a lightbox when clicking an image).

Thank you for your consideration!, Jan

**Comment by lhorakov** [comment]
Done
