### ISSUE TITLE
The OpenSCAP, scap-workbench, and scap-security-guide Open HUB project statistics images seem to be "cut off" at their bottoms

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#135]
The Open HUB project statistics images provided on the:
```
Home > Features > Open Source Community
```
page (in the section <i> The open source way help us to develop and grow fast </i> seem to be "cut off" at their respective bottoms). Picture of current state:

![screenshot-1](https://cloud.githubusercontent.com/assets/8414918/10887043/489df78e-8185-11e5-9471-a0755daaf2f9.png)

Note: Notice how "more at Open HUB" part of the respective image (for all three cases of OpenSCAP, scap-workbench, and scap-security-guide tools) is cut off at the bottom.

It would be nice if these images could be updated / replaced with some more appropriately looking ones.

Thank you for your consideration! Jan

**Comment by lhorakov** [comment]
Done
