### ISSUE TITLE
Photos for OpenSCAP Portal

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#136]
Hi everyone. We are trying to choose some photos for OpenSCAP Portal. They should be able to be cropped at top or bottom or both, because banners are slight and long, not very height. These are portals from which we can choose free photos and use them for free:
https://picjumbo.com/
https://unsplash.com/
http://www.gratisography.com/

**Comment by shawndwells** [comment]
What context will the photos be used in?

**Comment by lhorakov** [comment]
We want to use them in banner at Home page. We want to say with them to users they they trust us, that we are real. During UX testing we found out, that if website is only from vector images, it may cause distrust and that potential customer could choose competitor solution based on that.

**Comment by lhorakov** [comment]
Based on UX Testing I'm postponing this task for later (after finish of UX Testing) and also there are a few opinions from people we are testing, that the pages of our competitors with photos look too much commercially. What is an different opinion comparing with last testing (of old site). Milestone 1.2 since now.

**Comment by lhorakov** [comment]
It's done. (See new 2 banners) :)
