### ISSUE TITLE
oscap-anaconda-addon page on fedora hosted can be decommisioned

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#14]
Documentation from fedorahosted page has been already migrated to the new portal page.

**Comment by mpreisler** [comment]
With no assignee I doubt this is going to get done in 2 days.

**Comment by isimluk** [comment]
Hello @vpodzime, Can you please look into this?

My take was that since we have decommission https://fedorahosted.org/oscap-anaconda-addon/ since we have http://www.open-scap.org/tools/oscap-anaconda-addon/ and http://www.open-scap.org/tools/oscap-anaconda-addon/doc/

However, I would love to see what do you think? Do we have everything important tracked on the new pages?

**Comment by mpreisler** [comment]
What do we mean by decommission in this case?

Would putting big links to the new site be enough? I think this solution would be better because people may still be linking to the old fedorahosted site.

**Comment by isimluk** [comment]
Indeed, they may. In that case, decommission would be to either

 * redirect to the new page.
 * or remove all the texts (so we do not maintain them) and put a link here for the new page

**Comment by isimluk** [comment]
Also in the process, we should make sure that all the texts from the old page are somewhat presented on the new page.

**Comment by vpodzime** [comment]
I'm not sure I can do the redirect. But I can definitely make sure everything is mirrored to the new page(s) and then remove the contents from the old pages. During that process, I'd like to also create some ``.rst`` files in the git repository with at least the basic documentation. Does that make sense?

**Comment by isimluk** [comment]
@vpodzime, indeed it makes a lot of sense. Thanks!

**Comment by jan-cerny** [comment]
Whole Fedorahosted was decommissioned, including OAA page.
