### ISSUE TITLE
acronyms lightbox inconsistency

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#140]
http://www.open-scap.org/security-policies/

At the bottom, USGCB is an acronym, PCI-DSS is not. We should make this consistent.

**Comment by lhorakov** [comment]
Yeah, USGCB is in blue and clickable, as an acronym, and PCI-DSS is only in bold. Is that Bold typography what bothers you?

**Comment by iankko** [comment]
@lhorakov 
> Yeah, USGCB is in blue and clickable, as an acronym, and PCI-DSS is only in bold. Is that Bold typography what bothers you?

Assuming the issue here is that "PCI-DSS" should display lightbox too (describing the PCI DSS guidance).

**Comment by lhorakov** [comment]
But we do not have PCI-DSS in acronyms: http://www.open-scap.org/resources/acronyms/

**Comment by iankko** [comment]
I woudl add them. Not PCI-DSS directly, but maybe rather "PCI DSS".

**Comment by iankko** [comment]
The acronym for "PCI DSS" is now described. Added it to ```securitypolicies``` page too, but when clicking on it, the text isn't displayed :(. @lhorakov Could you hopefully inspect why that's the case? (maybe some ID needs to be changed yet).

Thanks, Jan.

**Comment by lhorakov** [comment]
Done

**Comment by iankko** [comment]
Thanks Lenka!
