### ISSUE TITLE
admin_url() returns https, but our users do not trust the certificate

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#141]
Check-out http://www.open-scap.org/resources/documentation/customizing-scap-security-guide-for-your-use-case/

And try to enter your comment. Captcha does not show. Captcha wants to fetch image over https. However, firefox will not show that.

Note: If you have already trusted open-scap's self signed certificate, it will work. However, for a new comer it will not.

**Comment by isimluk** [comment]
Ok, there is a bigger problem to tackle. The WP provides a function `admin_url`. That function returns URL that either starts with https or http. We need to fix what this function returns. This function is used across the plugins and controllers.

https://codex.wordpress.org/Function_Reference/admin_url

**Comment by lhorakov** [comment]
![screenshot from 2015-11-10 18-05-17](https://cloud.githubusercontent.com/assets/13556662/11069470/94c35be8-87d6-11e5-8005-ce033aedc07e.png)
![screenshot from 2015-11-10 18-05-25](https://cloud.githubusercontent.com/assets/13556662/11069471/94cf29e6-87d6-11e5-92cf-b11489594a64.png)

**Comment by mpreisler** [comment]
Lets disable comments before we get https cert which should be soon from what I have heard from letsencrypt.

Please avoid adding filters and more cruft into the theme if at all possible. Otherwise it will bite is in the future and the site will become un-maintainable.

**Comment by lhorakov** [comment]
Done

**Comment by isimluk** [comment]
Sorry about being blunt here. But what exactly has been "Done"?

Did we make admin_url() to return http version?

https://codex.wordpress.org/Function_Reference/admin_url

admin_url() function is used not only by capcha.

**Comment by lhorakov** [comment]
That we will have https, but now we dont need any changes in admin_url(), we will use other type of comments on website. They don't need https.

**Comment by mpreisler** [comment]
I'd say this is `wontfix`, once we have TLS certs in place it becomes a feature that it returns `https` :-)

**Comment by mpreisler** [comment]
It's a feature now, we have trusted TLS 1.2 cert in place.

**Comment by isimluk** [comment]
Martin, to which issue I can refer to when looking into TLS 1.2 cert progress?

**Comment by isimluk** [comment]
Ah, I found it #133.
