### ISSUE TITLE
openscap user manual got lost for users

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#145]
A lot of our users come directly to http://www.open-scap.org/page/Documentation and they expect to get openscap user manual, as they used to. However finding that user manual is hard. The redirect to static.open-scap.org might be confusing

You need to know it is called user manual. Otherwise you have no chance. Perhaps we can put latest manual of each tool directly to the page/Documentation

Just my $0.02

**Comment by jan-cerny** [comment]
@isimluk I agree with you. This is very similar issue as closed issue https://github.com/OpenSCAP/website/issues/93

**Comment by isimluk** [comment]
Ah right. I forgot about that. So it would be really helpful if we changed `view manuals` button to just show:
 * Scap-workbench manual (link http://static.open-scap.org/scap-workbench-1.1/)
 * OpenSCAP base manual (link http://static.open-scap.org/openscap-1.0/oscap_user_manual.html)

And nothing more. I think this would greatly improve discoverability of the manuals.

**Comment by lhorakov** [comment]
Done. Also with optimization for JS disabled. Unfortunately, for JS disabled we cannot produce those tutorilas automatically. But, they can be easily actualized by copying generated html on JS enabled. More at wiki - maintenance

**Comment by lhorakov** [comment]
Close if its done pls

**Comment by jan-cerny** [comment]
I got error 404

**Comment by lhorakov** [comment]
Now it's working. Thx

**Comment by mpreisler** [comment]
> Done. Also with optimization for JS disabled. Unfortunately, for JS disabled we cannot produce those tutorilas automatically. But, they can be easily actualized by copying generated html on JS enabled. More at wiki - maintenance

The tutorials aren't added there using javascript, they are generated server-side. I don't see why we need js-enabled to list them.

**Comment by lhorakov** [comment]
When I left the catlist there only (the button had to go in JS disabled, that's clear) they wasn't showing up. It wasn't working.

**Comment by lhorakov** [comment]
Ou, now, that was another. This was just 2 latest manuals with links there.
