### ISSUE TITLE
Tarball download link missing

### ISSUE THREAD

**Issue by c-spicer** [OpenSCAP/website#147]
On the page https://www.open-scap.org/tools/openscap-daemon/ , 'download tarball' should probably be a link to download the tarball

**Comment by isimluk** [comment]
Thanks for the report!
Actually, the OpenSCAP-daemon has been added to Fedora a few days ago. So we need to revisit these instructions.

**Comment by mpreisler** [comment]
Lenka, the command for installation of OpenSCAP-daemon is `dnf install openscap-daemon` on Fedora. It's not available elsewhere yet. Could you add that to the Download and Tools pages?

**Comment by lhorakov** [comment]
I have updated it on all pages: Tool->OpenSCAP Daemon, Download (in Download also for JS dis).
Done.
