### ISSUE TITLE
OpenSCAP Base apt-get install info incorrect for current Debian versions

### ISSUE THREAD

**Issue by josephbisch** [OpenSCAP/website#149]
Debian >= Jessie has a libopenscap8 library. Currently, the download page lists libopenscap0, which wasn't available in Debian since Squeeze, which is now oldoldstable.

So I think that the download page should either say libopenscap8, or even better would be to list that libopenscap8 is available for Debian Jessie and up, libopenscap1 is available for Wheezy, and libopenscap0 is available for Squeeze.

**Comment by mpreisler** [comment]
Fixed, I used `libopenscap8` everywhere.
