### ISSUE TITLE
SCAP Security Guide apt-get install info for Debian is wrong

### ISSUE THREAD

**Issue by josephbisch** [OpenSCAP/website#150]
The download page for SCAP Security Guide for Debian says to install scap-security-guide. There appears to have never been any such package in Debian and there definitely isn't currently one, so the download page shouldn't instruct users to try to install that package.

**Comment by iankko** [comment]
Thank you for your report, Joseph. I have replaced that information with text like:
* ```The SCAP Security Guide package is not available on the Debian distribution yet. Refer to: https://wiki.debian.org/SCAPGuide for updated information. ``` for the case of Debian icon / distribution, and with text
* ```The SCAP Security Guide package is not available on the Ubuntu distribution yet. Refer to: https://wiki.debian.org/SCAPGuide for updated information. ``` for the case of Ubuntu icon / distribution.

Should you want to have the above text changed in some way -- please let us know. Also kindly let us know, once the situation changed (the package is already included in Debian / Ubuntu distributions).

Thank you for reporting this!

Regards, Jan.

**Comment by iankko** [comment]
There's one occurrence of the very same information on the Download page yet. Will update that one too.

**Comment by iankko** [comment]
Fixed now on both pages:
* ```Home > Security Policies > SCAP Security Guide ```, and
* ``` Home > Download``` (item for SCAP Security Guide)
