### ISSUE TITLE
Tweets

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#151]
Tweets at http://www.open-scap.org/resources/ are often not displayed when I'm testing users. Actually they never were active. Only change is that in that time I'm not logged in by ethernet but by wifi connection to ***. Do you know why it could happen?

**Comment by iankko** [comment]
From https://www.quora.com/Twitter-will-not-load-when-used-with-my-WiFi-connection-at-home-I-have-tried-the-Twitter-app-from-my-cell-and-tablet-and-the-Twitter-site-from-my-laptop-In-all-three-cases-when-I-try-to-connect-with-WiFi-it-doesnt-connect-What-can-be-the-problem

looks the issue might be DNS settings related. I would double-check your DNS settings when using wire and wireless network connections, and ensure Twitter is resolved when using the wireless one.

**Comment by lhorakov** [comment]
It's question of my personal settings and it's working on other computers be wifi, so I'm closing it as solved.
