### ISSUE TITLE
Make Systems Management more visible

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#156]
In /Tools we are going to add some graphics to Systems Management to make it more visible.

**Comment by jan-cerny** [comment]
Also please consider to change the text here to explain that systems management can be used to scan more systems in parallel.

**Comment by lhorakov** [comment]
The design part is done. Still missing some sentence about parallel scanning: http://www.open-scap.org/tools/ : in basic description of Systems Management

**Comment by isimluk** [comment]
The old language was:
```Use OpenSCAP with your systems management solution of choice as Red Hat Satellite 6 (Foreman), Red Hat Satellite 5 (Spacewalk), RH Access Insights, and Preupgrade Assistant.```

The new language could read
```if you want to audit multiple systems at once or if you are simply looking into advnced deployment options, please take a look at OpenSCAP integration with systems management solutions as Red Hat Satellite 6 (Foreman), Red Hat Satellite 5 (Spacewalk), RH Access Insights, and Preupgrade Assistant.```

**Comment by jan-cerny** [comment]
This can be reviewed by @cipherboy when he will do the grammar check.
We think that the sentence proposed by @isimluk is not the best wording.
@yuumasato suggested that the more verbose text could go to the https://www.open-scap.org/tools/systems-management/ page

**Comment by cipherboy** [comment]
Proposed changes:

On the https://www.open-scap.org/tools/systems-management/ page:

Old:
```html
<div class="col-md-9 blueText quoteTitle">
      <h2>Use OpenSCAP with your systems management solution of choice</h2>
</div>
```
```html
<div class="col-md-9">
      <h2 class="blueText quoteTitle">Use OpenSCAP with your systems management solution of choice:</h2>
      <p>By integrating OpenSCAP with a centrally administered systems management solution, compliance scans can be conducted in parallel and on a repeated basis. This makes compliance easier and reduces the administrative overhead of manual scanning. By aggregating results in a central place, you can easily see the complete state of compliance across your entire organization. Below are several featured solutions with OpenSCAP integration.</p>
</div>
```

On the https://www.open-scap.org/tools page:

> Use OpenSCAP with your systems management solution of choice as Red Hat Satellite 6 (Foreman), Red Hat Satellite 5 (Spacewalk), RH Access Insights, and Preupgrade Assistant.

> Use OpenSCAP with a systems management solution such as Red Hat Satellite 6 (Foreman), Red Hat Satellite 5 (Spacewalk), RH Access Insights, or Preupgrade Assistant to centralize and ease compliance across your entire organization.

**Comment by jan-cerny** [comment]
@cipherboy That looks awesome!

**Comment by cipherboy** [comment]
@jan-cerny Thanks! Updated the website and closing this issue. :)
