### ISSUE TITLE
Systems Management naming

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#157]
In http://www.open-scap.org/tools/systems-management/ we should rename to titles from:
Red Hat Satellite 6 (Foreman) to Foreman (Red Hat Satellite 6),
the same with Spacewalk

**Comment by mpreisler** [comment]
Why?

**Comment by lhorakov** [comment]
Because the name of tool is actually Foreman and Spacewalk and it's used in RHEL6 or RHEL5. Now, hope you are sitting :D, 2 users thought that Red Hat Satellite 6 and Red Hat Satellite 5 are the names of tools. Running in Foreman and Spacewalk. Sorry for laughing :D So just for those who are totally totally new in this, we should make it to look and feel correctly.

**Comment by lhorakov** [comment]
We will make "Red Hat" with <h4> and Satellite with <h2>

**Comment by mpreisler** [comment]
Consider using < small > instead, < hX > has an important meaning for search engines, web readers for the blind, ... < hX > should never be used for formatting.

**Comment by lhorakov** [comment]
Ok. But it probably will not look as I wanted.

**Comment by mpreisler** [comment]
With the power of CSS everything is possible! :-)

**Comment by lhorakov** [comment]
Yes it is, but if you think about it: you have a headline and you want to make one part of headline smaller and one bigger. And you have tools for that, you do not have to write css even if to write it is so easy. Those h4, h3, h2, h1 are created for headlines. It is headline. Why we cannot use it? Our CSS file has more than 1200 lines, and that is our CSS. We also have Bootstrap's CSS.

**Comment by mpreisler** [comment]
< h3 > ABC < /h3 > < h4 > BCD < /h4> means BCD is a subheader of ABC. If we created a TOC it would be

```
- some h1
   - some h2
     - ABC
        - BCD
```

The other way around is even more bizarre, the first header would be a subheader of the previous N-1 header.

**Comment by lhorakov** [comment]
Ok, I get this reasoning. So I'm going to make it by CSS.

**Comment by lhorakov** [comment]
Done. http://www.open-scap.org/tools/systems-management/
