### ISSUE TITLE
Acronyms lightbox

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#160]
Add to each acronym window a link to See more acronyms.

**Comment by isimluk** [comment]
Actually, what is the benefit for the user seeing all the acronyms?

I feel, that having a link for more details would be even more valuable. For example in XCCDF acronym, we should link to our description at http://www.open-scap.org/features/scap-components/ . Similar to OVAL, ARF, SCE, etc.

For USGCB, PCI-DSS, acronym, we could link a tutorial.

**Comment by lhorakov** [comment]
We can add both links. 

The purpose of putting there a link of Acronyms page is that users will know that there is some general page with acronyms. For those users who don't prefer design/ad-look it can be another sign that the page is trustful.

And yes, I don't see why we shouldn't add links to those acronyms which we have more described already..

**Comment by jan-cerny** [comment]
Just an idea: Is there a possibility to more advertise the "Acronyms" page?

**Comment by lhorakov** [comment]
Now we have button in each acronym lightbox which will guide users to acronym page. Also we can add "Continue -> " to any acronym text which would send users to any other page with more information about that acronym.

**Comment by isimluk** [comment]
This has been done. Thanks!

Closing.
