### ISSUE TITLE
Wrong text formating

### ISSUE THREAD

**Issue by msrubar** [OpenSCAP/website#162]
At the [oscap anaconda page](http://www.open-scap.org/tools/oscap-anaconda-addon/doc/) there is a wrong formatting of commands in black. For example take a look at the first `%addon org_fedora_oscap`.

**Comment by lhorakov** [comment]
Ok, now it's better. You can close.

Explanation: There is an css class called nice-par2, which has to make similar 2 paragraphs next to each other, and inside this class cannot be used <p> or <div> or anything else than <span>. And <span> isn't showing the code so nice, as <p> f.e. So the only thing I could do with that was to add a non-breakable space, to be sure that the code will not be cut in half.

**Comment by jan-cerny** [comment]
The kickstart snippet is still wrong. I don't know kickstart syntax, but I suppose that each kickstart rule should start on a new line.

**Comment by lhorakov** [comment]
I don't know what do you mean. :D

**Comment by msrubar** [comment]
Take a look at this:
https://msrubar.fedorapeople.org/Selection_005.png
https://msrubar.fedorapeople.org/Selection_006.png

**Comment by lhorakov** [comment]
It's only in chrome, I didn't see it before. Here's the issue: I cannot remove it without breaking whole structure. Will think about it a while.

**Comment by msrubar** [comment]
Oh, I didn't know the issues was already reported. What is the number of the issue?

**Comment by lhorakov** [comment]
:D no, it was said rhetorically... like here is my problem :D.

**Comment by jan-cerny** [comment]
The kickstart snippet in section 1.2 is still wrong in both Firefox and Chrome.

**Comment by lhorakov** [comment]
Kickstart snippet is corrected. That line unfortunately cannot be corrected still. Don't know how. But I will solve it later.

**Comment by lhorakov** [comment]
It's done! Yeaah! Party!
