### ISSUE TITLE
Bad layout of the Tools page on certain screen sizes

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#163]
http://www.open-scap.org/tools/

If this page is viewed in a small window, eg. a half of the screen, SCAPTimony is out of layout. It should be displayed same as other components.

**Comment by mpreisler** [comment]
Can't reproduce this issue in Google Chrome on Fedora 23 and Android 6. What did you use for testing?

**Comment by jan-cerny** [comment]
@mpreisler I use Firefox 42 on Fedora 23.

**Comment by isimluk** [comment]
I can confirm on Fedora 22, firefox 42.

**Comment by lhorakov** [comment]
Fixed. Check it someone please to be sure we do not have this problem anymore. Thank you for your contribution!

**Comment by jan-cerny** [comment]
LGTM. Closing.
