### ISSUE TITLE
Missing page oval__variable_8c.html

### ISSUE THREAD

**Issue by msrubar** [OpenSCAP/website#165]
I was searching some information for local_variable element of OVAL and found this:

http://www.open-scap.org/doc/oval__variable_8c.html

**Comment by lhorakov** [comment]
And what you cliked and where are you going exactly?

**Comment by jan-cerny** [comment]
Which source refers to this page? Google search? Or some page has a link to this?

**Comment by msrubar** [comment]
Google search: 
https://www.google.cz/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=oval_variable&es_th=1

**Comment by lhorakov** [comment]
It is very possible that in old webpage was some information about this and as we changed it, the subpage with such link which google remembers doesn't exist anymore.

**Comment by jan-cerny** [comment]
It is a link to automatically generated documentation for OpenSCAP API. I suggest not solving this and waiting till Google forgets that link.

**Comment by isimluk** [comment]
Google search now points to the correct document. Closing.
