### ISSUE TITLE
Include user manual also for OpenSCAP 1.2.X

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#166]
http://static.open-scap.org/ contains user manual only for version 1.0.8.
It would be great to have there user manual  also for latest OpenSCAP 1.2.7 there,
because it differs in some paragraphs

**Comment by isimluk** [comment]
Nice catch! I agree that we should publish the manual for 1.2.x

However, I propose we publish only one manual and that being the 1.2.x. I feel that there is close to zero differences between the manuals. And thus having multiple versions adds a little value to the user -- while it may add a bit of confusion.

**Comment by jan-cerny** [comment]
@isimluk Originally I have thought that we should have only one version of the user manual.
I would agree with you now, but your idea is going against comments in https://github.com/OpenSCAP/openscap/pull/222, where it is explained that we should have instructions in manual only in branch where they are applicable.

**Comment by isimluk** [comment]
Right, I see.

Still, I feel there is a slight distinction between these two things.
* We should keep user manual close to the code in each branch. That is my reading of  OpenSCAP/openscap#222. That is engineering process and our virtue. This can save us potential trouble going forward (we can ship the right manual to the right downstream).
* On the other hand, for the website different rules may apply. Consumers of code(windows instructions)/manual may have different mindset. Good websites present just current information. The information that is targeted for majority of users is often highlighted. The information for minorities is usually harder to reach. So this is how the successful websites are being build. We now have only very slight differences between of user manuals between the versions. So, I we could try to pick just one manual and publish it.

Still, these are just my thoughts and $0.02.

**Comment by jan-cerny** [comment]
This is already solved on https://static.open-scap.org/ .
