### ISSUE TITLE
OpenSCAP logo slogan

### ISSUE THREAD

**Issue by lhorakov** [OpenSCAP/website#167]
We can increase trust by adding a word "security" into our logo. My idea is to add it into logo directly, because our competition has it there also.
Imagine logo of OpenSCAP which we are already using and after text part I would add something like:
"Certified security tool"
"Security for your system"
"Security tools for you"
"Security tools"
"Certified security"

any ideas more?

Advice: is important to have it short

**Comment by isimluk** [comment]
Audit, Fix and be Merry.

**Comment by iankko** [comment]
> Audit, Fix and be Merry.

+1 from me for this one.

**Comment by lhorakov** [comment]
That's good slogan, but may be it should contain word "security" because it's the word our users are searching for and it improves trust in us.

**Comment by lhorakov** [comment]
Done. Now cannot be seen, because of Christmas logo. But here is how it looks:
![main_logo_slogan](https://cloud.githubusercontent.com/assets/13556662/11894298/94e40cf4-a576-11e5-9309-5937e0695f2f.png)

**Comment by lhorakov** [comment]
Ok, you can't see that :D... here is printscreen
![screenshot from 2015-12-18 11-01-51](https://cloud.githubusercontent.com/assets/13556662/11894336/c91ea90c-a576-11e5-9e38-f76e8601ee4a.png)

**Comment by isimluk** [comment]
Wow! This is cool! Thank You!!!
