### ISSUE TITLE
Strange ordering of items in Features/Vulnerability Assessment

### ISSUE THREAD

**Issue by pbokoc** [OpenSCAP/website#172]
Hi, this is a minor thing but it's pretty odd.

Near the top of http://www.open-scap.org/features/vulnerability-assessment/ , the set of image links to known high-profile vulnerabilities (Heartbleed, Shellshock, etc.) should be moved below the 6 white boxes.

Right now the images are in the middle of other content. The text above the images ends with "These include:", and continues below in the white boxes - the vulnerability links are interrupting the flow of information. Moving the images down would improve the flow of information, and it would also bring this page in line with Features/Security Compliance, where there's also a set of image links, but placed below the white boxes.

**Comment by jan-cerny** [comment]
@pbokoc I agree with you. The `These include:` really should refer to the white boxes, not to the logos.
@lhorakov Could you edit the layout?

**Comment by lhorakov** [comment]
Thx, Done
