### ISSUE TITLE
google search of `oscap` does not bring us to the top

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#175]
I think we should try to improve it. Many people just call us oscap and they may well search for it.

**Comment by cipherboy** [comment]
Per results in Summer of 2018, I believe this to be resolved. OpenSCAP appears in the top 1-3 non-ad results on all major providers:

 - [Google](https://www.google.com/search?q=oscap)
 - [Bing](https://www.bing.com/search?q=oscap)
 - [DuckDuckGo](https://duckduckgo.com/?q=oscap)
 - [Yahoo](https://search.yahoo.com/search?p=oscap)
