### ISSUE TITLE
Document OpenStack/RHEL-OSP/7/ on choosing policy page

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#176]
@iankko has recently released https://github.com/OpenSCAP/scap-security-guide/releases/tag/v0.1.28 that bring a new SSG profile.

Now we should make sure that
* it is build on static.open-scap.org by jenkins
* http://static.open-scap.org/ contains the link to it
* http://www.open-scap.org/security-policies/choosing-policy/ contains the link to it

**Comment by mpreisler** [comment]
PR https://github.com/OpenSCAP/scap-security-guide/pull/1079 will fix the first task when it's merged.

**Comment by mpreisler** [comment]
``- it is build on static.open-scap.org by jenkins``
``- http://static.open-scap.org/ contains the link to it``
- http://www.open-scap.org/security-policies/choosing-policy/ contains the link to it
