### ISSUE TITLE
Link the oscap user manual to static.open-scap.org

### ISSUE THREAD

**Issue by msrubar** [OpenSCAP/website#18]
For now the links for user manual at OpenSCAP Base points to github. After make install will build the manual I'll edit the job on the Jenkins and correct the links so they point to the static.open-scap.org.

**Comment by mpreisler** [comment]
This was about http://www-rhopenscap.rhcloud.com/resources/documentation/ I believe and was fixed by linking the manuals to static.open-scap.org

I am not sure what the Jenkins comment is about.

**Comment by msrubar** [comment]
I think Jenkins wasn't building the manual at that moment but it's all fixed now.
