### ISSUE TITLE
CSS on static.open-scap.org should color the panels till the botton of the page

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#180]
Reproducer:
 * go to http://static.open-scap.org/
 * Ctrl + (several times)
 * page down

Result:
 * the color panels are not painted till the bottom of the page

**Comment by jan-cerny** [comment]
The same issue appears if you have small window size.

**Comment by lhorakov** [comment]
Problem solved! Using CSS3 only: http://static.open-scap.org/
Closing.

**Comment by jan-cerny** [comment]
@lhorakov Beautiful! Thank you.
