### ISSUE TITLE
Please create open-scap.org page banner for the upcoming SSG #3 WorkShop (2016-03-14)

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#181]
There's this SSG Q/A Contributor WorkShop #3 coming on Monday, 2016-03-14 from 10:00am - 12:00pm EDT:
&nbsp; &nbsp; [1] https://lists.fedorahosted.org/archives/list/scap-security-guide@lists.fedorahosted.org/thread/GXKQNUMJDVH3UANAJYRH556B4E2SDROI/#GXKQNUMJDVH3UANAJYRH556B4E2SDROI

Further information is available at dedicated wiki page:
&nbsp; &nbsp; [2] https://github.com/OpenSCAP/scap-security-guide/wiki/SCAP-Security-Guide-Contributor-WorkShop

Interested attendees are expected to register for this event via this Google form:
&nbsp; &nbsp; [3] http://goo.gl/forms/p2jPy1kccl

It would be great if we could create a banner for open-scap.org page, so it would pop up when people visit that page.

**Comment by iankko** [comment]
@lhorakov 
Lenka, could you possibly look at this && come out with a proposal?

Thank you, Jan.

**Comment by lhorakov** [comment]
Is it going to be in Brno? Like people will have to come to some place in RH building - according to Presentation: to come)?

**Comment by iankko** [comment]
@lhorakov 
> Is it going to be in Brno?

Hi Lenka, no it won't be in Brno. It will be virtual webinar over BlueJeans.

Interested attendees are only expected to register here:
&nbsp; &nbsp; http://goo.gl/forms/p2jPy1kccl

Thanks, Jan.

**Comment by lhorakov** [comment]
![screenshot from 2016-03-01 14-32-04](https://cloud.githubusercontent.com/assets/13556662/13428387/6c48fc7c-dfba-11e5-8605-9e30c61d1fcb.png)

What do you think about this? Text can be changed as you wish to be.

**Comment by isimluk** [comment]
I think it is perfect! Thank You!

**Comment by iankko** [comment]
@lhorakov 
Agree with Simon. This looks very nice to me. Great work!

> What do you think about this? Text can be changed as you wish to be.

The text is actually exact enough (we don't want to describe topics of a concrete instance in more detail since they are subject of slight changes / adjustments). But you could add the date && time information there, if possible? (so people won't get an impression, they can subscribe / register anytime)

The datetime is Monday, 2016-03-14 from 10:00am - 12:00pm EDT

Thanks a lot!!, Jan

**Comment by lhorakov** [comment]
It's updated. You can check it here: https://www.open-scap.org/
Is it ok for you?

**Comment by iankko** [comment]
@lhorakov 
> It's updated. You can check it here: https://www.open-scap.org/
Is it ok for you?

Looks brilliant!! Thanks a lot (I will send a re-remainder right away).

Thanks, Lenka.

**Comment by iankko** [comment]
And closing the issue yet (for proper tracking). The current banner more than very well meets the expectations of this ticket.
