### ISSUE TITLE
-- is rendered as – in code blocks sometimes

### ISSUE THREAD

**Issue by dahaic** [OpenSCAP/website#185]
See example on https://www.open-scap.org/resources/documentation/customizing-scap-security-guide-for-your-use-case/ at the very bottom of the page

What is displayed:
–tailoring-file TAILORING_FILE

Should be:
--tailoring-file TAILORING_FILE

Note: There is more of them, so I guess it's not a typo.

**Comment by jan-cerny** [comment]
@dahaic thank you very much for opening this issue

**Comment by jan-cerny** [comment]
Enclosing the text into `<code>` element seems to be helpful.

**Comment by jan-cerny** [comment]
This one particular occurrence on this URL https://www.open-scap.org/resources/documentation/customizing-scap-security-guide-for-your-use-case/ is fixed. But there might be others on other pages. Please investigate if it still appears somewhere and fix it. If the problem does not occur anywhere, then feel free to close this issue.

**Comment by matejak** [comment]
Done, there were couple of dashes left. `<code>` or `<pre>` work well as dash protectors.
