### ISSUE TITLE
SSL certificate for www.open-scap.org has expired

### ISSUE THREAD

**Issue by deno** [OpenSCAP/website#187]
Server Key and Certificate #1
Subject	static.open-scap.org 
Fingerprint SHA1: d916a44395c6e1beb3eaef124cf4f64fceb8fe3d
Pin SHA256: w2x7U7eF3T1l4tvp8UYf3Aiw7JaNRltLzOFmColNf5Y=
Common names	static.open-scap.org
Alternative names	static.open-scap.org www.open-scap.org
Valid from	Mon, 09 Jan 2017 17:15:00 UTC
Valid until	Sun, 09 Apr 2017 17:15:00 UTC (expired 15 hours and 5 minutes ago)   EXPIRED
Key	RSA 2048 bits (e 65537)
Weak key (Debian)	No
Issuer	Let's Encrypt Authority X3 
AIA: http://cert.int-x3.letsencrypt.org/ 

https://www.ssllabs.com/ssltest/analyze.html?d=www.open-scap.org

**Comment by mpreisler** [comment]
Thanks for letting us know! I have renewed the cert a few hours ago.
