### ISSUE TITLE
Broken Links on http://www.open-scap.org/security-policies/choosing-policy/

### ISSUE THREAD

**Issue by PCnetMD** [OpenSCAP/website#188]
Not sure where this needs to be posted.

The following links under the "**Red Hat Enterprise Linux 7**" drop-down in the "**Security policies available in the SCAP Security Guide**" section are broken (404 error):

STIG for Red Hat Enterprise Linux 7 Server
STIG for Red Hat Enterprise Linux 7 Server Running GUIs
STIG for Red Hat Enterprise Linux 7 Workstation
United States Government Configuration Baseline (NIAP OSPP v4.0, USGCB, STIG)

**Comment by jan-cerny** [comment]
Hi @PCnetMD 
Thanks for letting us know. These things have been changed and renamed in last release of SCAP Security Guide.  I have updated the links. Hopefully it works now.
