### ISSUE TITLE
SCAP Undefined

### ISSUE THREAD

**Issue by fpr3** [OpenSCAP/website#189]
The full _Security Content Automation Protocol_ expansion of the portal's essential SCAP acronym is absent from:
- the [home page](www.open-scap.org), 
- the SCAP-linked popup under the [home page](www.open-scap.org) "Standards" heading, and even
- the  [Acronyms](https://www.open-scap.org/resources/acronyms/) page.

Deep on the [Security Compliance](https://www.open-scap.org/features/security-compliance/) page there is a link to NIST where the expansion is correctly observed -- Security Content Automation Protocol (SCAP). The acronym expansion should appear in each of the locations noted above for the benefit of uninitiated visitors to the site.

While related to Issue #161, the magnitude here is greater than any ancillary acronym definitions.  Also, falling under the stated UX Designer Contributor axiom, "Sometimes you can find a mistake which can be easily fixed" , this might better stand alone to be quick closed.

**Comment by jan-cerny** [comment]
Thank you very much for reporting this.

**Comment by fpr3** [comment]
Excellent edits/additions. Thanks!
