### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by ybudimirov** [OpenSCAP/website#190]
SSL cert expired:
![2017-12-29_183719](https://user-images.githubusercontent.com/12114831/34441905-55570ab0-ecc7-11e7-9eb5-aecf35ac5aec.jpg)
https://www.ssllabs.com/ssltest/analyze.html?d=www.open-scap.org

**Comment by mpreisler** [comment]
Thx for letting us now. Certs have been renewed.
