### ISSUE TITLE
"Smart/directional" quotes in code blocks

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/website#192]
Similar to #185...

On this page: https://www.open-scap.org/features/other-standards/sce/

Under `Reporting reasons when check fails` heading, `1. use <check-import> element`:

```<check-import import-name=”stdout” />```

is a smart/directional quote instead of a regular quote that is used in XML... We should find and correct instances of this where possible.

**Comment by matejak** [comment]
I have fixed that occurrence (`<code>` or `<pre>` tags do the job), but it is impossible to search for double quotes, as it is probably the most used character in the HTML source. I poked around for some time, and couldn't find any other converted double quotes, so I am closing the issue, let's reopen it if smart quotes are rediscovered.
