### ISSUE TITLE
Description of SSG - License

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/website#195]
(I don't feel comfortable editing this particular description as an outgoing intern).

On this page: https://www.open-scap.org/security-policies/

The current text for SSG is:
> An open source project creating and providing SCAP security policies for various platforms – namely Red Hat Enterprise Linux 6 and 7, Fedora, Firefox, and others. The project is public domain and the policies it provides can be used freely by anyone.

In particular, I'm not sure "public domain" is correct as [SSG has a BSD-3 clause](https://github.com/OpenSCAP/scap-security-guide/blob/master/LICENSE).

This appears to be the only page with this problem.

**Comment by jan-cerny** [comment]
Thanks for pointing this out. SSG used to be public domain in past, but now it is using a BSD license. I have fixed that on the website.
