### ISSUE TITLE
DISA profile doubles audit rules RHEL 7.6 (auid unset and 4294967295) and prevents augenrules to run 

### ISSUE THREAD

**Issue by mightyjordi** [OpenSCAP/website#196]
I just found the following bug in RHEL 7.6 DISA STIG. Red Hat has officially filed it in BugTracker.  https://bugzilla.redhat.com/show_bug.cgi?id=1667108
HIGH PRIORTY

OPENSCAP remediation script fails to remediate issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1667108

For questions contact me
Jordi R
mynicepc@gmail.com

**Comment by ggbecker** [comment]
Hi Jordi,

Thank you for opening this issue.

We are aware of this issue and actually there is already a fix for that:
https://github.com/ComplianceAsCode/content/pull/3692

For future issues you may encounter I recommend you to open a ticket [here](https://github.com/ComplianceAsCode/content/issues/new) which is the place for issues related to you are having. The main project is called 'content' under the organization ComplianceAsCode [here is the link](https://github.com/ComplianceAsCode/content).

I am closing this issue as it is not related to this project and also it is already fixed.

Best regards.
