### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Aevyz** [OpenSCAP/website#197]
On the [Policy Choosing Page](
https://www.open-scap.org/security-policies/choosing-policy/) the following link is broken. You can find it under Red Hat Enterprise Linux 7 -> United States Government Configuration Baseline (USGCB / STIG) – DRAFT

http://static.open-scap.org/ssg-guides/ssg-rhel7-guide-ospp-rhel7.html

**Comment by ggbecker** [comment]
The correct link is: http://static.open-scap.org/ssg-guides/ssg-rhel7-guide-ospp.html

**Comment by ggbecker** [comment]
Fixed.

**Comment by Aevyz** [comment]
@ggbecker Sorry to annoy, but more links on the page seem broken. In the same category `Common Profile for General-Purpose Systems` & `Criminal Justice Information Services (CJIS) Security Policy` both seem to 404

**Comment by ggbecker** [comment]
Hello, thanks for the feedback.

It seems that the webpage contains lots of broken links.

I've run a tool to check for them through the whole website and found several occurrences.

This report will be considered for future fixes.

Thank you again.
