### ISSUE TITLE
SCE wrong syntax

### ISSUE THREAD

**Issue by thaygiaoth** [OpenSCAP/website#199]
Please correct SCE syntax at this link

https://www.open-scap.org/features/other-standards/sce/

<check system="http://www.open-scap.org/page/SCE">

Correct syntax: <check system="http://www.open-scap.org/page/SCE"> **(remove www.)**

![image](https://user-images.githubusercontent.com/10233106/69021670-333fb880-09eb-11ea-9930-b6890a48f954.png)

![image](https://user-images.githubusercontent.com/10233106/69021728-68e4a180-09eb-11ea-84f7-cce3cd58354b.png)

I'm openscap newbie. So I spent several hours for this bug :D

WARNING: Skipping rule that requires an unregistered check system or incorrect content reference to evaluate. Please consider providing a valid SCAP/OVAL instead of http://www.open-scap.org/page/SCE

Tks

**Comment by jan-cerny** [comment]
@thaygiaoth Thank you, great catch! I have fixed that and I have also done a few minor updates on that page.

**Comment by thaygiaoth** [comment]
Tks, it's just a typo

Have  nice day!
