### ISSUE TITLE
Migrate Ideas page somewhere to git

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#2]
We should create/improve developer documentation for OpenSCAP project.

We should take pages
```
    http://www.open-scap.org/page/Contribute/Ideas
    http://www.open-scap.org/page/Contribute
```

And perhaps merge them into CONTRIBUTE.md in OpenSCAP/openscap repo.

**Comment by mpreisler** [comment]
I'd prefer to have them as tickets with some tag attached. Doing TODOs or issues in a plain text file in a repo sounds really stone age.

**Comment by isimluk** [comment]
I agree, Martin. I'll file the tickets.

It seems that these pages are the only pieces from old portal that do not have new portal alternative.

**Comment by isimluk** [comment]
Done.
