### ISSUE TITLE
Github link for Windows Scap Workbench download is down

### ISSUE THREAD

**Issue by unraveller82** [OpenSCAP/website#200]
Hi,

Github link for Windows SCAP Workbench download is down. 

Can someone look into it? Thanks!

**Comment by jan-cerny** [comment]
Hi @unraveller82,  can you tell us which link on which page?

I have checked the download button on http://www.open-scap.org/tools/scap-workbench/ which links to http://www.open-scap.org/tools/scap-workbench/download-win32 which is a redirect to https://github.com/OpenSCAP/scap-workbench/releases/download/1.1.5/scap-workbench-1.1.5-1.msi and it worked for me. Could it be that there was a temporary outage on GitHub side?

**Comment by unraveller82** [comment]
yes its working now. could be a temp outage. Thanks
