### ISSUE TITLE
Page SCE - 404s

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/website#204]
Per http://www.open-scap.org/features/other-standards/sce/ and current OpenSCAP documentation, the correct value on a SCE check (`<check system=<value>`) is http://open-scap.org/page/SCE. However, currently this page 404s. Maybe it should redirect to the former? Should the value be updated in OpenSCAP?

**Comment by jan-cerny** [comment]
Maybe there was some glitch in redirects but the redirect works for me now.

**Comment by cipherboy** [comment]
Works for me now too, weird!
