### ISSUE TITLE
Add favicon to portal

### ISSUE THREAD

**Issue by ybznek** [OpenSCAP/website#25]
Please, add some favicon to portal web.

**Comment by mpreisler** [comment]
I'll take this and upload icons based on http://www-rhopenscap.rhcloud.com/wp-content/uploads/2015/07/openscap-base.png

This should be good enough for GA. Lenka can take it later and change the images. Will be easier since there will be no need to set up the HTML5 code.

**Comment by mpreisler** [comment]
Holy crap this stuff is very complex for just being a bunch of images. In the end I used http://realfavicongenerator.net/ set up all the HTML5 code and uploaded the results into site root (this is recommended and most supported). The result is decent enough for GA IMO.

Tracking improvement of the situation in #105
