### ISSUE TITLE
Create lightbox for acronym at page 'X'

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#27]
If you need lightbox for an acronym at your page, please put it to the comments section.

**Comment by mpreisler** [comment]
We can search for this automatically using Wordpress. Go to Dashboard -> Pages. On top of the page on the right you can see "Search pages". Insert acronym of your liking -- for example CVE -- and hit search. It will filter pages and only show those that have CVE in them.

For some acronyms that are too short this approach sucks but it works well for a ton of them.

**Comment by lhorakov** [comment]
Done. Never again :D ...
