### ISSUE TITLE
Tutorial: Perform vuln scan of RHEL6 machine

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#30]
http://openscap-lhorakov.rhcloud.com/resources/documentation/perform-vulnerability-scan-of-rhel-6-machine/

sources:
http://www.open-scap.org/page/Documentation#How_to_run_vulnerability_scan_on_Red_Hat_Enterprise_Linux
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sect-Practical_Examples.html#sect-Auditing_Security_Vulnerabilities_Example

optional sources:
http://isimluk.livejournal.com/5655.html

The tutorial should reflect latest developments around bzip2, datastreams, split RHSAs per product. Ping Simon or Martin for info on these, AFAIK there is no good source yet for these.

**Comment by isimluk** [comment]
Also use RHEL6 specific XML file: https://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_6.xml

**Comment by isimluk** [comment]
@jan-cerny I have reviewed the text at https://www-rhopenscap.rhcloud.com/resources/documentation/perform-vulnerability-scan-of-rhel-6-machine/

It looks fine! The only thing I would add is to describe what "true" and "false" means in the results.

Then, I think you can close this ticket.

**Comment by jan-cerny** [comment]
@isimluk Thanks your for the review. I have added the description, Closing.
