### ISSUE TITLE
Tutorial: scan a docker container for vulnerabilities or compliance

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#31]
http://openscap-lhorakov.rhcloud.com/resources/documentation/scan-a-docker-container-for-vulnerabilities-or-compliance/

Explain oscap-docker, practical example with USGCB and vuln scan. Link to vuln scan of RHEL6 for more info about vulnerability assessment.

Sources:
https://github.com/OpenSCAP/openscap/blob/maint-1.2/utils/oscap-docker.8
https://github.com/OpenSCAP/container-compliance
(but keep in mind that oscap-docker is now part of OpenSCAP, this repo will likely be decommissioned at some point!)

**Comment by isimluk** [comment]
Everybody agrees to close this.
