### ISSUE TITLE
Tutorial: Make RHEL7 PCI-DSS compliant

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#32]
http://openscap-lhorakov.rhcloud.com/resources/documentation/make-a-rhel7-server-compliant-with-pci-dss/

Sources:
http://static.open-scap.org/ssg-guides/ssg-rhel7-guide-pci-dss.html
@iankko 
OpenSCAP evaluation remediation docs

**Comment by msrubar** [comment]
The text of the tutorial and screenshots should be ready for a review. A formatting and design still has some issues.

Should we mention the remediation or learn users how to use it in some other tutorial and point them to it?

**Comment by mpreisler** [comment]
I really like the style of this text, it's clear, to the point and very specific. Kudos!

I would mention remediation as the last chapter. The tutorial is about putting a RHEL7 server into compliance so remediation is the logical last step.

**Comment by msrubar** [comment]
Remediation section should be done now. I'd like to ask @mpreisler to confirm the info about passwords (search 'password' on the page). If everything is alright then @lhorakov can finish the formatting part.

**Comment by isimluk** [comment]
@mpreisler, ping

**Comment by mpreisler** [comment]
Sorry about late response, the remediation content looks good to me. I am leaving this open because @msrubar is tracking the wireframe part in this ticket.

**Comment by lhorakov** [comment]
http://www-rhopenscap.rhcloud.com/resources/documentation/make-a-rhel7-server-compliant-with-pci-dss/
Done
