### ISSUE TITLE
Tutorial: RHEL5 and USGCB compliance

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#33]
http://openscap-lhorakov.rhcloud.com/resources/documentation/rhel5-and-united-states-government-configuration-baseline-usgcb/

Sources:
http://www.open-scap.org/page/Documentation#How_to_Evaluate_United_States_Government_Configuration_Baseline_.28USGCB.29_on_Red_Hat_Enterprise_Linux_5

**Comment by isimluk** [comment]
This is currently available through OpenSCAP user manual.

See https://github.com/OpenSCAP/openscap/blob/maint-1.0/docs/manual/manual.adoc#how-to-evaluate-united-states-government-configuration-baseline-usgcb

Do we want to migrate this to a tutorial form?

**Comment by mpreisler** [comment]
I take tutorials as more self-starting than the user manual. They can go into more examples and be more "hand holding" than the manual.

There could be value in having both.

**Comment by mpreisler** [comment]
This has to be done with `oscap` because RHEL5 doesn't have workbench.

**Comment by mpreisler** [comment]
RHEL5 is no longer supported by SSG, let's close this ticket. We are focusing on RHEL6 and newer.
