### ISSUE TITLE
Tutorial: DISA STIG compliance on RHEL5

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#34]
http://openscap-lhorakov.rhcloud.com/resources/documentation/disa-stig-compliance-on-rhel5/

Sources:
http://www.open-scap.org/page/Documentation#How_to_Evaluate_Defense_Information_Systems_Agency_.28DISA.29_Security_Technical_Implementation_Guide_.28STIG.29_on_Red_Hat_Enterprise_Linux_5

**Comment by yuumasato** [comment]
Closing as obsolete.
The source link doesn't exist anymore.
