### ISSUE TITLE
Tutorial: Security compliance of RHEL7 docker containers

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#35]
http://openscap-lhorakov.rhcloud.com/resources/documentation/security-compliance-of-rhel7-docker-containers/

Sources:
https://jlieskov.wordpress.com/2015/07/17/scanning-container-images-on-red-hat-enterprise-linux-atomic-host-v-7-using-oscap-docker-and-scap-security-guide/

**Comment by isimluk** [comment]
This is done. Thanks!
