### ISSUE TITLE
Migrate the app to rhopenscap domain

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#36]
Currently we host using the Free plan on @lhorakov 's account. I have applied for employee subscription and was granted Silver plan for OpenSCAP. I have created the `rhopenscap` domain on OpenShift with this plan and have given @lhorakov rights to administer it.

Advantages of `rhopenscap`:
* the app will never idle
* it is a paid plan so the support is better
* more storage, faster website - load balancer and all those other fancy things
* OpenSCAP team has access to it
* sits right next to the `static` app that serves `static.open-scap.org`

How to do this:
* Create snapshot of the app on @lhorakov 's account
* Create a Wordpress app on rhopenscap
* Restore snapshot on the new app

It will kill all the `openscap-lhorakov.rhcloud.com` links so I suggest doing this right before GA.

**Comment by lhorakov** [comment]
What's GA? Great A-Day? :D

**Comment by iankko** [comment]
@lhorakov 
> What's GA? Great A-Day? :D 
General Availability.

But your interpretation is great too (never look at this like that :))

**Comment by mpreisler** [comment]
We decided to redirect all old links via `.htaccess`. This will enable us to do this transition sooner.

I am aiming to transition the app next week.

**Comment by mpreisler** [comment]
Hi,
today between 17:00 CEST and 18:00 CEST I will be moving
http://openscap-lhorakov.rhcloud.com to http://www-rhopenscap.rhcloud.com

The main reason for this is to move from free bronze plan to supported
and much faster silver plan. This gives us more storage and avoids
idling / stalling.

I will do my best to redirect all links and make the transition as
seamless as possible. The old links will perma-redirect to the new site.

Consequences for everyone working on the portal:

You can make changes to openscap-lhorakov.rhcloud.com until 17:00 CEST.
Do not work on www-rhopenscap.rhcloud.com before 18:00 CEST!
Please avoid doing any changes to the web between 17:00 and 18:00 CEST.
Only change www-rhopenscap.rhcloud.com after 18:00 CEST.

All logins will be the same on the new site.

Sorry for the inconvenience and thanks for your understanding!

**Comment by mpreisler** [comment]
Done. Please use http://www-rhopenscap.rhcloud.com from now on.

I have done the redirects as well, via `.htacess` in the root directory of the old openshift application.
