### ISSUE TITLE
Ensure all portal pages will work properly for both: 1) JavaScript enabled 2) JavaScript disabled cases

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#42]
The use of JavaScript language in pages brings a lot of capabilities when compared to completely static HTML pages.

On the other hand, many government agencies / corporate policies might require JavaScript support to be disabled in web browsers the system to be compliant.

Therefore we should ensure all portal pages work correctly (provide equivalent user experience) in both cases:
* JS is enabled,
* JS is disabled.

**Comment by lhorakov** [comment]
Working on that right time, for like 6 hours now. Next time we will create only static page... :D

**Comment by lhorakov** [comment]
Home :white_check_mark:
Getting Started :white_check_mark:
Download :white_check_mark:
Security compliance :white_check_mark:
Vulnerability assessment :white_check_mark:
Documentation :white_check_mark:
Install PCI-DSS compliant RHEL-7.2 using oscap Anaconda Add-on :white_check_mark:
Customizing SCAP Security Guide for your use-case :white_check_mark:
Security compliance of RHEL7 Docker containers :white_check_mark:
Make a RHEL7 server compliant with PCI-DSS :white_check_mark:
Perform vulnerability scan of RHEL 6 machine :clock3:
Evaluate remote machine for USGCB compliance :clock3:

**Comment by lhorakov** [comment]
It's finally done! Process can be seen in previous comment. Closing
