### ISSUE TITLE
Migrate jenkins how-to on portal page or somewhere on the github

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#44]
Today, we have some developer info behind firewall. No reason for hiding this.

**Comment by isimluk** [comment]
has wrote a nice tutorial on jenkins, still waiting for redaction review.

**Comment by isimluk** [comment]
Here is the Zbyňek's blog concerning jenkins https://blog-zbynek.rhcloud.com/2015/10/12/contribution-to-openscap-with-jenkins/

I feel this material is perfect. I have returned to the page many times and I have pointed out this page to others under numerous occasions. However, I feel this page is a little bit invisible for general public.

Is there any place on the website where we could refer to this blog? Alternatively, is there a place in the information architecture of the website, where the copy would fit in?

**Comment by matejak** [comment]
We host Jenkins documentation on https://github.com/OpenSCAP/jenkins. It could be improved, but that's another issue.
