### ISSUE TITLE
Use "OSCAP Anaconda Add-On" as the official name for OAA

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/website#52]
The Red Hat Enterprise Linux 7.0 release notes:
&nbsp; &nbsp; [1] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/pdf/7.0_Release_Notes/Red_Hat_Enterprise_Linux-7-7.0_Release_Notes-en-US.pdf

refers to oscap anaconda addon as "OSCAP Anaconda Add-On" (see page #3 of [1] or page #45 of [1]).

We should be consistent in the naming the tool and use the same notation.

**Comment by jan-cerny** [comment]
I think they should rename it in that pdf, but not we in the portal. What does "OSCAP" mean? Nobody knows that. Where we talk about it? We either have OpenSCAP or the `oscap` cmdline utility (but that is called *OpenSCAP Base* in all portal texts). I know that security people love acronyms, but I think we should not invent another weird acronym without any purpose.

**Comment by iankko** [comment]
@jan-cerny 
> I think they should rename it in that pdf, but not we in the portal. What does "OSCAP" mean? Nobody knows that. Where we talk about it? We either have OpenSCAP or the oscap cmdline utility (but that is called OpenSCAP Base in all portal texts). I know that security people love acronyms, but I think we should not invent another weird acronym without any purpose.

Just for the record, we aren't inventing another weird acronym here. ```oscap-anaconda-addon``` is the official current RPM name used for installation (by ```yum``` or ```dnf```).

**Comment by jan-cerny** [comment]
@iankko OK, I am sorry, I did not know that this is already an official name. You are correct that we should use the official name.

But on the other hand, my opinion is that this official name haven't been chosen well because of that "OSCAP" acronym. So I suggest this should be explained to the user somewhere on the portal.

**Comment by isimluk** [comment]
What is the exact problem here? Where do we have incorrect name on the portal?

**Comment by jan-cerny** [comment]
@isimluk The problem was that we had many variants of add-on name on portal and each was different. But I think everything is correct now. At least at visible places. We can close the ticket.

**Comment by isimluk** [comment]
Thank You!!
