### ISSUE TITLE
Remove dependency of the theme on wpbootstrap

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#58]
`wpbootstrap` is outdated, uses bootstrap2 from 2012. We moved to bootstrap3.

Since `wpbootstrap` is never going to be updated, lets stop depending on it and move everything into our own custom theme called `openscap`.

**Comment by mpreisler** [comment]
I have created a new theme simply called `openscap`, copied everything inside. Now we don't depend on wpbootstrap as far as Wordpress is concerned.

However we still depend on some of the paths to SVG images, still need to change those to `openscap`.

**Comment by mpreisler** [comment]
I have prefixed old stuff with `old_dont_touch_` and deleted all non needed bits from `wpbootstrap_openscap`. I have only left the `img` folder there.

**Comment by isimluk** [comment]
Martin, what remains to be done here? Looks completed to me, but not sure.

**Comment by mpreisler** [comment]
This is not completed yet, there are links in the content that rely on stuff in wpbootstrap. I don't think it's strictly 1.0 but would be nice to have this cleanup before release. I am moving to 2.0 because strictly speaking we can skip this and release the portal.

**Comment by isimluk** [comment]
Tentatively moving to 1.1. Feel free to revert.

**Comment by lhorakov** [comment]
I've searched for:"wpbootstrap-" in all pages and removed it. Now it can be close imho. The img file with svg images in "openscap" already had those files.

**Comment by mpreisler** [comment]
There still could be deps in the theme PHP files.

**Comment by lhorakov** [comment]
I removed it from each php file. There was 4 links left, which I rewrote to "openscap" instead of "wpbootstrap-openscap"... But there is one file left: "functions.php" with 4 "wpbootstrap" inside. I'm afraid to work with it because I don't know if it will affect something. Can you look at it?

**Comment by mpreisler** [comment]
I have checked it and it's fine, both functions are defined in the file, this is not a dependency on the other theme.
