### ISSUE TITLE
resources/documentation wireframe & visuals

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#61]
As discussed on the meeting.

How do we split the three sections?

I expect a very few people to click `OpenSCAP API documentation` but it has to be there. Perhaps we can have two columns with user manuals on one side and tutorials on the other with the API docs being linked after that, hidden a bit.

**Comment by lhorakov** [comment]
http://openscap-lhorakov.rhcloud.com/resources/documentation/
Is this enough?

**Comment by mpreisler** [comment]
Yes. The user manual links are missing though.

Does it make sense to just replicate what's on http://static.open-scap.org/ ? That way we will have to update it on 2 locations which sucks.

**Comment by isimluk** [comment]
I vote for closing this one for 1.0 and keeping track of missing manuals in #69. Please re-open if you disagree.

**Comment by mpreisler** [comment]
I disagree so I am obediently reopening ;-) The manuals section does nothing and it's confusing. The first thing I tried was clicking all over it to discover the manuals.

**Comment by msrubar** [comment]
What if we would just put a button there poiting to the static and drop the API part? Most of the developers probably wouldn't be looking for the API on the portal I think. Please take a look at the [page ](https://www-rhopenscap.rhcloud.com/resources/documentation/)I added the button.

**Comment by isimluk** [comment]
@msrubar, perfect!
@mpreisler, manuals section is no longer confusing. I just again think this can be closed. ;-)

**Comment by mpreisler** [comment]
Yup, I will keep this closed now ;-)
