### ISSUE TITLE
SVGs require fonts to render correctly

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#63]
For example http://openscap-lhorakov.rhcloud.com/wp-content/themes/wpbootstrap-openscap/img/banner-1.svg looks different on Windows and Fedora. Windows lacks the font so it gets rendered with some serif fallback font.

A solution would be to convert the text to curves.

**Comment by lhorakov** [comment]
I have converted all svgs with text to vector. Before GA. Done.
