### ISSUE TITLE
Clean the 404 list

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/website#64]
See https://openscap-lhorakov.rhcloud.com/wp-admin/tools.php?page=redirection.php&sub=404s

It lists recent 404 errors by hit count. It's a pretty cool way to discover issues in links or images. Before GA we should strive to minimize this list as much as we can.

**Comment by msrubar** [comment]
I don't have permissions to access the page.

**Comment by mpreisler** [comment]
Most of these issues come from the theme PHP files or CSS which only admins can change.

If you don't have access to the page please ignore this ticket for now.

**Comment by lhorakov** [comment]
Done, left 2 thing which I don't know what it is. From know there shouldn't be anything. I will check it frequently to eliminate possible non-catched-errors.
