### ISSUE TITLE
Firefox and JRE policies are not generated at static.open-scap.org

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#66]
In Security policies available in the SCAP Security Guide:
*Java Runtime Environment (JRE) 1.6.0, 1.7.0 and 1.8.0* is now in the Firefox category. That is wrong. It should be a separate category. This category will contain only one item (Upstream Java Runtime Environment (JRE) STIG). Firefox category will also contain only one item (Upstream Firefox STIG).

**Comment by isimluk** [comment]
I have removed JRE and Firefox from the page (as we do not have HTML guides generated online for them.

So we need to:
1) Start generating these guides on jenkins
2) amend index.html at static.open-scap.org
3) Edit choosing-policy portal page and include links to newly generated policies

**Comment by mpreisler** [comment]
This is SSG upstream issue. Jenkins just runs `make` and collects the results.

**Comment by mpreisler** [comment]
Agreed that this would be a "nice to have" but do we have someone who will take this and fix it in SSG? I am willing to review but don't have time to implement it myself.

@jan-cerny @msrubar ?

If nobody takes it this week I will postpone this to 1.2.

**Comment by jan-cerny** [comment]
Done.
