### ISSUE TITLE
Do not use "THIS" or "here" as a link text

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#67]
On Systems management page, we have texts like this:
> See THIS for more info.

Where THIS is a clickable link to an external page.
My opinion is we should not do that, we can put some sensible text instead of word *THIS*.
For example:

> See *Access Insights Homepage* for more info.

**Comment by jan-cerny** [comment]
This page explains why: http://www.jakpsatweb.cz/jak-psat.html#odkazy

**Comment by jan-cerny** [comment]
Systems management page has been fixed. I haven't checked other pages, so I leave this ticket opened.

**Comment by isimluk** [comment]
Thanks! I vote for closing this ticket for now. :-)

**Comment by lhorakov** [comment]
I searched for all links like >THIS< >HERE< - it's not caps sensitive. And there's only one link left which I'm removing right now. So issue is solved. Close
