### ISSUE TITLE
Improve "GET IT" page

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#68]
I have some ideas about the "GET IT" page. I would be happy if you consider them:
* Put *Choose your platform* and *Choose your tool* above the respective comboboxes, not uder them. I think that is more logical when we read from top to bottom, so first say "Choose .." and after give the options.
* I don't like that heading of this page is "Learn it & Get the source", because **main purpose** of this page is to tell userhow to **download and install** the software. Learning or getting the source code are in my opininion not as important options. Moreover these two will be still very visible if you remove the heading, because they have nice big buttons.
* In SCAP Security guide, I would change the wording to "Security policies" instead of "content".
* Would it be possible that the page don't change its height when selection an option in combobox? Can the page have fixed height?

**Comment by lhorakov** [comment]
Done before GA.
