### ISSUE TITLE
Documentation page shall refer to all the user manual

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#69]
We have couple of manuals but they are not linked from the documentation page.

**Comment by isimluk** [comment]
Nice to have in 1.0, should be too much of work.

**Comment by msrubar** [comment]
also see #61

**Comment by isimluk** [comment]
Actually, I see this is as valid ticket still (see my comment in #69 about #61 tracking manuals missing on this page).

Not re-opening. @jan-cerny has filed a same issue (#93) with much better description.
