### ISSUE TITLE
/resources/support/ page should include this tracker

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#75]
This issue tracker is used for reporting issues with OpenSCAP portal. Perhaps we can put this in front of user and let them file requests/ideas directly.

**Comment by mpreisler** [comment]
We might want to move the tracker to github.com/OpenSCAP/website from here

**Comment by isimluk** [comment]
I am ok with that. I think I am able to move this repository there. Any blocker for not doing right now?

**Comment by mpreisler** [comment]
I don't see any, as long as it's communicated it should be fine.

**Comment by isimluk** [comment]
Removing myself as a assignee, I don't expect to have time allocation for this. Anyone can take it.

**Comment by lhorakov** [comment]
I have added a this to 404 page and also to resources/support/github issues this:
Do you think that you found a bug on our website? Please, help us to improve and create an issue on  <a class="light-link" href="https://github.com/OpenSCAP/website/issues/new">Github</a>

 I'm thinking about add this into more sites, but not sure where/how. It's question to think. For me this issue can be closed.

**Comment by lhorakov** [comment]
Perfect, I'm added to issue which can be closed :D

**Comment by mpreisler** [comment]
@lhorakov Check the title of this ticket, I don't think this can be closed.

**Comment by lhorakov** [comment]
Resources -> Support has to have github.com/OpenSCAP/website tracker

This page: http://www.open-scap.org/resources/support/ has this: GitHub Issues with this: Do you think that you found a bug on our website? Please, help us to improve and create an issue on Github (with linked Github word to https://github.com/OpenSCAP/website/issues/new)

**Comment by mpreisler** [comment]
Ah, you are right, I didn't notice that.
