### ISSUE TITLE
"Get it" page does not work in Google Chrome

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#77]
Choose tool and choose platform does not do anything. So it is not possible to display other information than how to install OpenSCAP Base on Fedora.
Issue appears on Google Chrome 45.0.2454.101 (64-bit) on Fedora 22 and on Google Chrome  45.0.2454.94 on Android 4.4.2.

**Comment by jan-cerny** [comment]
This issue is very similar to an problem with Google Chrome that I had in HTML report. See this commit message https://github.com/OpenSCAP/openscap/commit/d8d7ff3460b1e0fba1d09d5f8a3ec48730e8a4ff

**Comment by ybznek** [comment]
Fixed, tested on FF 41.0.1 on Fedora 22 and Chrome Version 45.0.2454.101 (64-bit) on Manjaro
