### ISSUE TITLE
Supply the "list tag" for each video we present on the page

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#82]
We have youtube list of all videos at https://www.youtube.com/playlist?list=PLHYsrwTE3Rofwk_cc7641QNhSF8JzPprE

When you supply this "list" tag to each video user is able to redirect to youtube portal and see all our videos automatically. Example of video url with list tag is https://www.youtube.com/watch?v=p4uNlzYld-Y&list=PLHYsrwTE3Rofwk_cc7641QNhSF8JzPprE&index=8

**Comment by lhorakov** [comment]
I don't understand, please explain what is needed to do?

**Comment by lhorakov** [comment]
Done
