### ISSUE TITLE
Migrate contribute.adoc to openscap.git

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#84]
Michal,

Thanks for writing contribute text at https://github.com/lhorakov/openscap-doc/blob/master/contribute.adoc We need a little more to finish this thing.

1) We can push this to openscap.git.
2) Than we can amend README.md to link to it (perhaps a github markdown can do a relative links, otherwise we can take absolute URL there.
3) Then we can update the link at the bottom of http://openscap-lhorakov.rhcloud.com/tools/openscap-base/ (see "I want to help with the developement")

Could you please look into this?

**Comment by msrubar** [comment]
Sure I will review the old text and take a closer look at it.

**Comment by isimluk** [comment]
Reopen. The task number 3 is not finished.

(note I usually prefer one ticket per issue/task, however, these task are dependent on each other, so they are tracked within single ticket).

**Comment by msrubar** [comment]
Thank you very much. I missed this one but it's fixed now.
