### ISSUE TITLE
Finish the open source comunity page

### ISSUE THREAD

**Issue by msrubar** [OpenSCAP/website#85]
I've been working on the open [source community page](https://www-rhopenscap.rhcloud.com/features/open-source-community/). I think it's ready from my point of view. There are still two parts that needs to be done and those are:

1. We provide free SCAP content - @iankko is probably the right person to write the page.
2. We are not vendor lock-in: @isimluk will describe it much better than me.

After it's done it could be ready for @lhorakov to do some ux magic.

**Comment by isimluk** [comment]
Too much tasks in a single ticket. That may result in nobody really taking this.

Imho, the missing texts can be done in 2.0. Let's focus on wireframe in 1.0.

**Comment by msrubar** [comment]
Split into 3 separate issues.
