### ISSUE TITLE
Make sure you're not using the "openscap-lhorakov.rhcloud.com" in URLs

### ISSUE THREAD

**Issue by msrubar** [OpenSCAP/website#86]
The links won't  work after we switch the domains! At least [this page](https://www-rhopenscap.rhcloud.com/resources/documentation/customizing-scap-security-guide-for-your-use-case/) does it! Not sure about others.

**Comment by mpreisler** [comment]
A good way to check this is to search for `openscap-lhorakov` in all the pages and all posts. Wordpress dashboard allows it.

https://www-rhopenscap.rhcloud.com/wp-admin/edit.php?s=openscap-lhorakov&post_status=all&post_type=post
https://www-rhopenscap.rhcloud.com/wp-admin/edit.php?s=openscap-lhorakov&post_status=all&post_type=page

Same goes for usage of `../` in URLs or even `http://www-rhopenscap.rhcloud.com`. Everything can be done using the `/something/somewhere` syntax and that is the most portable.

I will keep this open for now, we will check this before release.

**Comment by mpreisler** [comment]
Have done another round of cleaning this up. A few more `rhcloud` instances cropped up in tutorials and pages. Fortunately it's easy to fix it in an automated way. Here is an updated set of queries to check for this issue:

https://www-rhopenscap.rhcloud.com/wp-admin/edit.php?s=rhcloud&post_status=all&post_type=post
https://www-rhopenscap.rhcloud.com/wp-admin/edit.php?s=rhcloud&post_status=all&post_type=page

**Comment by mpreisler** [comment]
Removing release blocker, the page works even with old URLs. Everything is redirected correctly.

**Comment by jan-cerny** [comment]
@mpreisler  Your two queries give no results. I think we can close this issue.

**Comment by mpreisler** [comment]
@jan-cerny I am keeping this open on purpose. Will check it again before GA.

**Comment by mpreisler** [comment]
No bad URLs as of 2015-11-02, closing.
