### ISSUE TITLE
Bold text in footer on anaconda add-on page

### ISSUE THREAD

**Issue by pbokoc** [OpenSCAP/website#88]
https://www-rhopenscap.rhcloud.com/tools/oscap-anaconda-addon/ has the entire footer (the "site map" thing at the bottom of the page) in bold. 

No other pages seem to have that, so ^ should be brought in line with the rest of the site.

**Comment by mpreisler** [comment]
There was a unclosed <strong> element on the page, it is fixed now. Thanks for reporting!
