### ISSUE TITLE
Improve documentation page

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/website#93]
http://www-rhopenscap.rhcloud.com/resources/documentation/

I think that this page isn't logical.

First problem is that when I click on "View manuals", I get to static.open-scap.org, but when I click on "View tutorials", tutorials are displayed below the button. This is inconsistent behavior. As a user, I would expect that those two similar buttons will cause similar action.

Second problem is that to view a manual, I must do **too many steps**: First get to Resources page, then to Documentation page, then click on View Manuals, then I got to static.open-scap.org, then I must choose one of them. Why not put the links directly to Documentation page? It is only 4 links.

I don't know what would be the best solution. I suggest removing the "VIew manuals" and "View tutorials" buttons and put the links to manuals/tutorials directly under the headings.

What do you think about this?

**Comment by isimluk** [comment]
Totally agree.

There is still work to be done. Also, I am not sure what happens when we write like 20 tutorials.

**Comment by jan-cerny** [comment]
@isimluk Nice to hear that we share opinion about this page :-)

Also, I would like to say that the "OpenSCAP Base API documentation" also could be reachable more easily if we don't point to static.open-scap.org, but put the links directly on the documentation page.

About 20 or more tutorials: We can solve this after such situation happens. We have 6 tutorials now. That's not so much. I think they can be visible directly. After, we can display the most popular and we can add a button "See others".

**Comment by lhorakov** [comment]
I've changes the look of buttons to difference those two parts. 
Number of steps to manuals is the same as for tutorials. Manuals has own page for better sharing for users. The will share the url of that page. Without tutorials.
