### ISSUE TITLE
UX review of resources page

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#94]
Hello Lenka,

I do confess. I have changed a wireframe on the https://www-rhopenscap.rhcloud.com/resources/ page. Please review the page and then accept/amend/revert/punish.

I collapsed news and documentation into a single container. Removed the video and included twitter timeline.

I did it all in single change, so you can easily revert it.

**Comment by jan-cerny** [comment]
@isimluk I like the Tweets section, it's great!

**Comment by lhorakov** [comment]
It's good idea, thank you. I would change only the high of the twitter window.
