### ISSUE TITLE
UX: different sortings at static.open-scap.org

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/website#95]
There is inconsistency.
 * APIs are sorted from the newest to the oldest
 * manuals are sorted from the newest to the oldest
 * guides are sorted from oldest to the newest

Please sort guides in order: Fedora Linux, RHEL7, RHEL6,...

**Comment by mpreisler** [comment]
This was also bugging me. Done. I kept the grouping by product but pushed newer versions up.

http://static.open-scap.org/
